export {default as Home } from "./home/page"
export {default as About } from "./about/page"
export {default as Contact } from "./contact/page"
export {default as Experience } from "./experience/page"
export {default as Blog } from "./blog/page"